### ISSUE TITLE
URL signature expired

### ISSUE THREAD

**Issue by rentainhe** [facebookresearch/EgoObjects#1]
Hello, it seems that the download link for the dataset is not working, could you please update the download link?

**Comment by zcck3rn3l** [comment]
> Hello, it seems that the download link for the dataset is not working, could you please update the download link?

Hi please find new link in updated README. Let me know if you still cannot download.

**Comment by rentainhe** [comment]
Thank u so much for fixing this, I can download the image and annotations now
